Task25/Task25/Controllers/GuestController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Task25.Models;
using Task25.BLL;
using System.Text.RegularExpressions;

namespace Task25.Controllers
{
    public class GuestController : Controller
    {
        readonly GuestService guestService;

        /// <summary>
        /// GuestController contstructor
        /// </summary>
        public GuestController()
        {
            guestService = new GuestService();
        }

        /// <summary>
        /// Action to redirect to the main page
        /// </summary>
        public ActionResult Index()
        {
            var reviews = guestService.GetListOrderedByPublicationDate();

            var reviewsMapped = new List<Models.Review>();

            foreach (var review in reviews)
            {
                reviewsMapped.Add(
                    new Review
                    {
                        AuthorName = review.AuthorName,
                        Content = review.Content,
                        Date = review.Date
                    }
                    );
            }

            return View(reviewsMapped);
        }

        /// <summary>
        /// Action to add a new review to the database
        /// </summary>
        [HttpPost]
        public ActionResult Create()
        {
            bool flag = true;
            Regex textRegex = new Regex("[A-Za-z]+");

            try
            {
                Match match = textRegex.Match(Request.Form["name"]);

                if (!match.Success)
                {
                    flag = false;
                }

                match = textRegex.Match(Request.Form["textReview"]);

                if (!match.Success)
                {
                    flag = false;
                }
            }
            catch
            {
                flag = false;
            }

            if (flag == true && ModelState.IsValid)
            {
                guestService.Create(Request.Form["name"], Request.Form["textReview"]);
            }

            return RedirectToAction("Index");

        }
    }
}

Task25/Task25/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/styles.css")
</head>
<body>
    <div class="wrapper">
        <header>
            <nav class="navbar navbar-expand-md navbar-light bg-light">
                <img class="navbar-brand" src="~/Content/logo.png">
                <p class="navbar-header mx-auto">Library</p>
            </nav>
        </header>
        <div class="main-block">
            <div class="container-fluid">
                <div class="col-10 float-left">
                    @RenderBody()
                </div>
                <div class="right-sidebar col-2 float-left text-center">
                    <ul>
                        <li>@Html.ActionLink("Main", "Index", "Home")</li>
                        <li>@Html.ActionLink("Comments", "Index", "Guest")</li>
                        <li>@Html.ActionLink("Form", "Index", "Form")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="container-fluid">
            <div class="row text-center">
                <p class="col-12">Kirill Shkuratiuk kirillshkuratiuk@gmail.com <br /> <a class="col-12" href="#top">Go back to top</a></p>
            </div>
        </div>
    </footer>
</body>
</html>